language: python
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - secure: "mNEcQCazeJ8+2ITZKPWrZlES8Jol/ZyLKAc1jFJJ2SE7naUK9VlryVOIMUPSqq+WvLItkVygyqI1PPWXBoaogvR+c4g8EIb+2DY8WtP4bbQBfULMnnuxYDg4fc2z7Uo93KZsXTtOgwUlqjzYOX/2Eb1/atINJNLfxEAQlHZznKriQ9nOrcnkCH8cB9PpuejdUg2C2j791uI1uCB2mTXuV3URD32XmNvd5wC0g+AaLqb8Y7CIcprmhBqdfJ7QvgxoAI1fEjQXTkO0OqqO+3k81oqjrridVqvC6MoU977zckDydRwMHM6JrpLOAenXjKXcOVk0vHrbDsHuPLFEQrqXsFhYILT5QdiuluZdfTPUrXO15pkSosk+xS29lhqnYH67l0tOVMcMyHlVvYCGNlwJ/hivrWeDz4DLYN6LYLsbWKQjYwiWWa9c98E7cGtKKyxDFj2iogs5E7cLo14Ut6ZYwusTVoQYwHZqoX1JoGNmm5bdlLDx5nOt/WYS3CyTTzLNVl7uPd+MUoz/cbPhIDZZP20KofDsfAvmLx8O/zFfiWOJQhQDK9udX8leB0IBdwRO3YeZlgUmafefGl/fvoQTk11iMq7/5nOP+JPjUqyz+iQ/PAYBRWDXfkWzUWs58TZktfPC6dnAjWp0YfOooYzWB+khBMk3uae+1G5b8ldpNW0="
    - secure: "GA0TTootNqXGnkHpYPmMQSPcGY8BvYJ1WdBFdMfmw9RvVnjb8rSNzeEaCAeFYooAC7F8oYEpDql9DwlrOeGv2JdbyHH5H5WGVw2KwyL8BO0Awo9cfECdgnp1bWXHSDxC99sS4o1IJdDrhSmNEXTV2yC0okARmrghaC/zlVQvimpZPUsRyrD0J7icJPBBBm6dBb3Wpy9rAg1TEH1FvN5BLfqZlqsfm4lw7ANSsIBJxD7MMAN+y9Zdsz/j2169p/3gAyRvDNLnsWzb0SrUgKJ3Hp+GQXYFHnRDwHhAViJqu4wkjJEuEXN24Hymt1wRrt1F7BWj8gX+JhRhhzKuSpEQmWJrH9IIILWGLtwL8zQ7WxuZZKL0EsjBK8VOrZSgnpI8LIVk4xlZESDEenx42y5GyvAkP2SdxP4MG8yHuJnD2z0MHYvAFRqBoxe8nVWEM3TxcefCiSR9SG+9AeR3MDfig3eYz01vE3/S8gN6EvF6bsSnpBPHi11C11mkcv1CSaAT/qk6FQe2gUKObFuOV/FrLxajgzt61b0uP3if50HScRGR8kRAyCk2UdF8zL5L5PjETsL4SEml2HD1SM296LLHLeB0B2SIdiTGsieu2m7duz/SPsSb7knpwNaAR67m+zZwMIKKQsqY41T9Rwtt3itKzOBgCmliU2fv/96Z2L6C4H0="
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/bob_dbmanage.py casme2 download
- ./bin/coverage run --source=bob.db.casme2 ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest docs sphinx
- ./bin/sphinx-build -b html docs sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
